import streamlit as st
import os
import sys
import json
from datetime import datetime

# Path setup
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
from modules.style import apply_vectis_style, get_station_header
from modules.unified_llm import UnifiedLLM

# Page Config
st.set_page_config(page_title="Mind Alchemy | EGO", page_icon="⚗️", layout="wide")

# Apply Style
apply_vectis_style()

# Header
st.markdown(get_station_header("19", "MIND ALCHEMY", "Idea Refinery & Transmutation"), unsafe_allow_html=True)

# State Management
if "refined_output" not in st.session_state:
    st.session_state.refined_output = ""
if "history" not in st.session_state:
    st.session_state.history = []

# Sidebar: History & Settings
with st.sidebar:
    st.header("📜 Transmutation Log")
    if st.button("Clear Output"):
        st.session_state.refined_output = ""
    
    st.markdown("--- ")
    st.caption("Select LLM Model in Control Center")

# Main Interface
col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("🧪 Raw Material (Input)")
    raw_text = st.text_area("Pour your chaotic thoughts here...", height=400, placeholder="Example:\nI want to create a new app for EGO but I'm not sure what features it should have. Maybe something about health? Or coding?")
    
    st.markdown("### ⚗️ Select Process")
    transmutation_type = st.selectbox(
        "Choose transmutation circle:",
        [
            ("Summarize", "Create a concise summary."),
            ("Actionable", "Extract a concrete task list."),
            ("Critic", "Provide critical feedback and identify weak points."),
            ("Expand", "Brainstorm related ideas and expand the concept."),
            ("Socratic", "Ask deep questions to clarify the thought."),
            ("Structure", "Organize into a structured markdown document.")
        ],
        format_func=lambda x: f"{x[0]} - {x[1]}"
    )
    
    process_btn = st.button("Transmute ⚡", type="primary", use_container_width=True)

with col2:
    st.subheader("💎 Refined Essence (Output)")
    
    output_container = st.empty()
    
    if st.session_state.refined_output:
        st.markdown(st.session_state.refined_output)
        st.markdown("--- ")
        st.caption("Generated by EGO LLM")

# Logic
if process_btn and raw_text:
    mode_key = transmutation_type[0]
    
    # Prompt Engineering
    prompts = {
        "Summarize": "You are a skilled editor. Summarize the following text concisely, capturing the core essence.",
        "Actionable": "You are a project manager. Extract actionable tasks from the following text and present them as a checklist.",
        "Critic": "You are a critical thinker. Analyze the following text, point out logical flaws, missing information, and potential risks.",
        "Expand": "You are a creative muse. Based on the following text, brainstorm 5-10 related ideas or features that could enhance it.",
        "Socratic": "You are Socrates. Do not answer, but ask 3-5 profound questions that will help the user clarify their own thinking regarding the following text.",
        "Structure": "You are a technical writer. Organize the following unstructured text into a clean, well-structured Markdown document with headers and bullet points."
    }
    
    system_prompt = prompts[mode_key]
    user_prompt = f"Text to process:\n{raw_text}\n\n---\n\nPlease perform the requested analysis/processing."

    with st.spinner(f"Transmuting using {mode_key} process..."):
        try:
            llm = UnifiedLLM(provider="ollama", model_name="phi4")
            # Simple generation call
            response = llm.generate(f"{system_prompt}\n\n{user_prompt}")
            
            st.session_state.refined_output = response
            
            # Save to history (optional future feature)
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            st.session_state.history.append({"time": timestamp, "mode": mode_key, "input": raw_text[:50]+"...", "output": response})
            
            st.rerun()
            
        except Exception as e:
            st.error(f"Transmutation failed: {str(e)}")

# Footer
st.markdown("--- ")
st.markdown("<div style='text-align: center; color: #666;'>EGO MIND ALCHEMY MODULE v1.0</div>", unsafe_allow_html=True)
