
import { Edge } from 'reactflow';
import { VisualNode } from './types';

export function generateC(nodes: VisualNode[], edges: Edge[]): string {
    let cCode = "#include <stdio.h>\n#include <stdlib.h>\n\n// Generated by Visual Coder (C)\nint main() {\n";

    const edgeMap: Record<string, string> = {};
    edges.forEach(edge => edgeMap[edge.source] = edge.target);

    let currentNode = nodes.find(n => n.type === 'start' || (n.data as any).realType === 'start');
    if (!currentNode) return "// Error: No Start Node";

    const visited = new Set<string>();
    let indentLevel = 1;

    while (currentNode) {
        if (visited.has(currentNode.id)) break;
        visited.add(currentNode.id);

        const { code, isBlockStart, isBlockEnd } = getNodeCCode(currentNode);

        if (isBlockEnd && indentLevel > 1) {
            indentLevel--;
            cCode += "    ".repeat(indentLevel) + "}\n";
        }

        const indent = "    ".repeat(indentLevel);
        if (code) cCode += indent + code + "\n";

        if (isBlockStart) indentLevel++;

        const targetId: string | undefined = edgeMap[currentNode.id];
        if (!targetId) {
            while (indentLevel > 1) {
                indentLevel--;
                cCode += "    ".repeat(indentLevel) + "}\n";
            }
            break;
        }
        currentNode = nodes.find(n => n.id === targetId);
    }

    while (indentLevel > 1) {
        indentLevel--;
        cCode += "    ".repeat(indentLevel) + "}\n";
    }

    cCode += "    return 0;\n}\n";
    return cCode;
}

function getNodeCCode(node: VisualNode): { code: string, isBlockStart?: boolean, isBlockEnd?: boolean } {
    const data = node.data;
    const type = (data.realType as string) || node.type;

    switch (type) {
        case 'start': return { code: "" };
        case 'print':
            const val = data.value || '""';
            const fmt = val.startsWith('"') ? "%s\\n" : "%d\\n";
            return { code: `printf("${fmt}", ${val});` };
        case 'var':
            const v = data.value || '0';
            const isStr = v.startsWith('"');
            const typeDecl = isStr ? "char*" : "int";
            return { code: `${typeDecl} ${data.variable || 'var'} = ${v};` };

        case 'math':
            return { code: `int ${data.variable || 'result'} = ${data.value || '0'};` };

        // Logic
        case 'if': return { code: `if (${data.condition || '1'}) {`, isBlockStart: true };
        case 'while': return { code: `while (${data.condition || '1'}) {`, isBlockStart: true };
        case 'for': return { code: `// For loop simplified\nfor (int i = 0; i < 10; i++) {`, isBlockStart: true };

        case 'function': return { code: `void ${data.label.replace('Def: ', '') || 'my_func'}() {`, isBlockStart: true };
        case 'return': return { code: `return ${data.value || '0'};` };

        case 'list': return { code: `// Arrays in C are static\nint ${data.variable || 'list'}[] = {${data.value?.replace('[', '').replace(']', '') || '0'}};` };
        case 'comment': return { code: `// ${data.code?.replace('# ', '') || 'Comment'}` };

        default: return { code: `// Unknown: ${type}` };
    }
}
