
import { Edge } from 'reactflow';
import { VisualNode } from './types';

const IMPORTS_MAP: Record<string, string> = {
    'random': 'import random',
    'math': 'import math',
    'os': 'import os',
    'sys': 'import sys',
    'json': 'import json',
    'time': 'import time',
    'datetime': 'from datetime import datetime',
    'np': 'import numpy as np',
    'pd': 'import pandas as pd',
};

export function generatePython(nodes: VisualNode[], edges: Edge[]): string {
    let pythonCode = "";
    let requiredImports = new Set<string>();

    // 1. Build Map of Edges (Source -> Target)
    const edgeMap: Record<string, string> = {};
    edges.forEach(edge => {
        edgeMap[edge.source] = edge.target;
    });

    // 2. Find Start Node
    let currentNode = nodes.find(n => n.type === 'start');
    if (!currentNode) {
        // Fallback: If no start node, maybe try to process sequentially if only one chain exists?
        // For now, strict: Needs Start Node.
        return "# Error: No 'Start' node found. Please drag a Start node to the canvas.";
    }

    pythonCode += "# Generated by Visual Coder (Systematic Python)\n\n";

    // 3. Traversal Loop
    // 3. Traversal Loop
    const visited = new Set<string>();
    let indentLevel = 0;

    while (currentNode) {
        if (visited.has(currentNode.id)) {
            pythonCode += "\n# [Cycle Detected] - Stopping traversal.\n";
            break;
        }
        visited.add(currentNode.id);

        // Generate Code for Current Node
        const { code, imports, isBlockStart, isBlockEnd } = getNodeCode(currentNode);

        if (isBlockEnd && indentLevel > 0) indentLevel--;

        const indent = "    ".repeat(indentLevel);

        if (code) {
            // Handle multi-line code (like raw blocks)
            const lines = code.split('\n');
            lines.forEach(line => {
                pythonCode += indent + line + "\n";
            });
        }

        if (isBlockStart) indentLevel++;

        imports.forEach(i => requiredImports.add(i));

        // Move to Next
        const targetId: string | undefined = edgeMap[currentNode.id];
        if (!targetId) break;
        currentNode = nodes.find(n => n.id === targetId);
    }

    // 4. Prepend Imports (Sorted)
    const sortedImports = Array.from(requiredImports).sort();
    const importHeader = sortedImports.join('\n');

    return (importHeader ? importHeader + "\n\n" : "") + pythonCode;
}

function getNodeCode(node: VisualNode): { code: string, imports: string[], isBlockStart?: boolean, isBlockEnd?: boolean } {
    const data = node.data;
    const imports: string[] = [];

    const effectiveType = (data.realType as string) || node.type;

    switch (effectiveType) {
        case 'start':
            return { code: "# --- Start ---", imports: [] };

        case 'print':
            return { code: `print(${data.value || '""'})`, imports: [] };

        case 'var':
            const val = data.value || 'None';
            return { code: `${data.variable || 'var'} = ${val}`, imports: [] };

        case 'list': // New
            return { code: `${data.variable || 'my_list'} = ${data.value || '[]'}`, imports: [] };

        case 'dict': // New
            return { code: `${data.variable || 'my_dict'} = ${data.value || '{}'}`, imports: [] };

        case 'math': // New
            return { code: `${data.variable || 'result'} = ${data.value || '0'}`, imports: ['import math'] };

        case 'python':
            const raw = data.code || "";
            Object.keys(IMPORTS_MAP).forEach(key => {
                if (raw.includes(key)) imports.push(IMPORTS_MAP[key]);
            });
            return { code: raw, imports };

        // Logic & Blocks
        case 'if':
            return { code: `if ${data.condition || 'True'}:`, imports: [], isBlockStart: true };

        case 'while': // New
            return { code: `while ${data.condition || 'True'}:`, imports: [], isBlockStart: true };

        case 'for':
            return { code: `for ${data.condition || 'i in range(10)'}:`, imports: [], isBlockStart: true };

        case 'try': // New
            return { code: `try:`, imports: [], isBlockStart: true };

        case 'except': // New idea: Maybe handle as separate block? For now just print
            return { code: `except Exception as e:\n    print(e)`, imports: [], isBlockEnd: true, isBlockStart: true };

        case 'function':
            // data.label usually has "Def: name"
            // We use label parsing or separate field. 
            // The addNode logic sets data.label="Def: name", and usually we'd want data.variable or value for name
            const funcName = data.label.replace('Def: ', '') || 'my_func';
            return { code: `def ${funcName}():`, imports: [], isBlockStart: true };

        case 'class': // New
            const className = data.label.replace('Class: ', '') || 'MyClass';
            return { code: `class ${className}:`, imports: [], isBlockStart: true };

        case 'return': // New
            return { code: `return ${data.value || ''}`, imports: [] };

        case 'import':
            return { code: (data.code || 'import os'), imports: [] }; // Usually handled in header, but inline is ok

        case 'comment':
            return { code: `${data.code || '# Comment'}`, imports: [] };

        default:
            return { code: `# Unknown Node: ${effectiveType}`, imports: [] };
    }
}
