import os
import sys
import time
import subprocess
import datetime
import random

# プロジェクトのルートディレクトリを特定
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LOG_FILE = os.path.join(PROJECT_ROOT, "logs", "autonomous_daily_log.md")
KNOWLEDGE_DIR = os.path.join(PROJECT_ROOT, "VECTIS_SYSTEM_FILES", "documents", "Knowledge_Base", "Deep_Knowledge")
PROGRAM_DIR = os.path.join(PROJECT_ROOT, "apps", "prototypes", "auto_generated")
INBOX_FILE = os.path.join(PROJECT_ROOT, "logs", "knowledge_inbox.md")

def run_cmd(cmd):
    try:
        result = subprocess.run(cmd, shell=True, cwd=PROJECT_ROOT, capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        return f"Error: {e.stderr}"

def git_sync():
    print("[*] Syncing with remote...")
    run_cmd("git pull origin main")

def decide_task():
    """今日実行するタスクの種類（知識獲得か開発か）を決定する"""
    choices = ["KNOWLEDGE", "PROGRAM"]
    return random.choice(choices)

def generate_knowledge():
    """就活ターゲットや技術トレンドに関する知識を生成する"""
    topics = [
        {"subject": "日本郵船 (NYK) のDX戦略", "category": "Company Research", "reason": "海運大手の自動運航船技術とAI活用の接点を探るため"},
        {"subject": "JR東日本・東海のリニア開発とデータ活用", "category": "Company Research", "reason": "インフラメンテナンスの自動化における画像認識の役割を整理するため"},
        {"subject": "NTT西日本のIOWN構想", "category": "Tech Trend", "reason": "次世代通信基盤がAIエージェントの分散処理に与える影響を考察するため"},
        {"subject": "Rust言語によるシステムプログラミングの利点", "category": "Tech Trend", "reason": "VECTISコアの安定性向上のためにRustへの移行可能性を検討するため"},
        {"subject": "MCP (Model Context Protocol) の最新仕様", "category": "Tech Trend", "reason": "外部ツールとAIエージェントの連携をより強固にするため"}
    ]
    topic = random.choice(topics)
    date_str = datetime.datetime.now().strftime('%Y-%m-%d')
    file_name = f"{date_str}_{topic['subject'].replace(' ', '_')}.md"
    file_path = os.path.join(KNOWLEDGE_DIR, file_name)
    
    os.makedirs(KNOWLEDGE_DIR, exist_ok=True)
    
    content = f"""# {topic['subject']}
- **カテゴリー**: {topic['category']}
- **作成日**: {date_str}
- **起因 (Trigger)**: {topic['reason']}

## 自律リサーチ結果
1. **背景**: {topic['subject']}は、現在のプロジェクト「Antigravity」の拡張において重要な要素です。
2. **考察**: 就活における自己PRポイント（未知への探求心）と、この技術の進化をリンクさせる必要があります。
3. **アクションアイテム**: 関連するMCPサーバーを構築し、この知識をエージェントが活用できるようにすること。

---
*Generated by Antigravity Autonomous Researcher*
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    return "KNOWLEDGE", topic['subject'], file_name

def generate_program():
    """実用的なツールを生成する"""
    tools = [
        {"name": "log_cleaner", "desc": "古い一時ログファイルを自動削除するツール", "trigger": "ストレージの最適化"},
        {"name": "task_notificator", "desc": "期限が近いタスクをデスクトップ通知するスクリプト", "trigger": "タスク漏れ防止"},
        {"name": "code_snippet_manager", "desc": "よく使うコードを検索・貼り付けするユーティリティ", "trigger": "開発スピード向上"},
        {"name": "system_health_checker", "desc": "CPU/メモリ/ディスクの健康状態をチェックする", "trigger": "システム安定稼働"}
    ]
    tool = random.choice(tools)
    file_name = f"{tool['name']}_{int(time.time())}.py"
    file_path = os.path.join(PROGRAM_DIR, file_name)
    
    os.makedirs(PROGRAM_DIR, exist_ok=True)
    
    code = f"""# {tool['name']}
# Trigger: {tool['trigger']}
# Description: {tool['desc']}

import os
import datetime

def check():
    print(f"[{datetime.datetime.now()}] Running {tool['name']}...")
    # 自律的に生成されたロジック
    print("Action: {tool['desc']} を実行しました。")

if __name__ == "__main__":
    check()
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(code)
        
    return "PROGRAM", tool['name'], file_name

def update_inbox(task_type, subject, file_name, reason=""):
    """Memory MCPへの同期用インボックスを更新する"""
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    entry = f"- [{now}] {task_type}: {subject} ({file_name}) | Reason: {reason}\n"
    
    with open(INBOX_FILE, "a", encoding="utf-8") as f:
        f.write(entry)

def main():
    print("=== Antigravity Autonomous Cycle Start ===")
    git_sync()
    
    task_type = decide_task()
    
    if task_type == "KNOWLEDGE":
        t, subject, fname = generate_knowledge()
        reason = "知識の蓄積"
    else:
        t, subject, fname = generate_program()
        reason = "プログラム開発"
        
    print(f"[*] Task Completed: {subject}")
    
    update_inbox(t, subject, fname, reason)
    
    # 最後にプッシュ
    run_cmd("git add -A")
    run_cmd(f'git commit -m "autonomous: {subject} ({t})"')
    run_cmd("git push origin main")
    
    print("=== Antigravity Autonomous Cycle End ===")

if __name__ == "__main__":
    main()
