
import { Edge } from 'reactflow';
import { VisualNode } from './types';

export function generateRust(nodes: VisualNode[], edges: Edge[]): string {
    let rustCode = "";

    // 1. Build Map
    const edgeMap: Record<string, string> = {};
    edges.forEach(edge => edgeMap[edge.source] = edge.target);

    // 2. Headless traversal logic (similar to Python but distinct syntax)
    let currentNode = nodes.find(n => n.type === 'start' || (n.data as any).realType === 'start');
    if (!currentNode) return "// Error: No Start Node";

    rustCode += "// Generated by Visual Coder (Rust)\nfn main() {\n";

    const visited = new Set<string>();
    let indentLevel = 1; // Start inside main()

    while (currentNode) {
        if (visited.has(currentNode.id)) break;
        visited.add(currentNode.id);

        const { code, isBlockStart, isBlockEnd } = getNodeRustCode(currentNode);

        if (isBlockEnd && indentLevel > 1) {
            indentLevel--;
            rustCode += "    ".repeat(indentLevel) + "}\n";
        }

        const indent = "    ".repeat(indentLevel);
        if (code) rustCode += indent + code + "\n";

        if (isBlockStart) indentLevel++;

        const targetId: string | undefined = edgeMap[currentNode.id];
        if (!targetId) {
            // Close any open blocks at the end of chain? 
            // Ideally we need proper tree traversal, but for linear chain:
            while (indentLevel > 1) {
                indentLevel--;
                rustCode += "    ".repeat(indentLevel) + "}\n";
            }
            break;
        }
        currentNode = nodes.find(n => n.id === targetId);
    }

    // Safety close
    while (indentLevel > 1) {
        indentLevel--;
        rustCode += "    ".repeat(indentLevel) + "}\n";
    }

    rustCode += "}\n";
    return rustCode;
}

function getNodeRustCode(node: VisualNode): { code: string, isBlockStart?: boolean, isBlockEnd?: boolean } {
    const data = node.data;
    const type = (data.realType as string) || node.type;

    switch (type) {
        case 'start': return { code: "" };
        case 'print': return { code: `println!("{}", ${data.value || '""'});` };
        case 'var': return { code: `let ${data.variable || 'var'} = ${data.value || '0'};` };
        case 'list': return { code: `let ${data.variable || 'list'} = vec!${data.value || '[]'};` };
        case 'dict': return { code: `// Dict not fully supported in simple transpiler\nlet mut ${data.variable || 'map'} = std::collections::HashMap::new();` };
        case 'math': return { code: `let ${data.variable || 'result'} = ${data.value || '0'};` };

        // Logic
        case 'if': return { code: `if ${data.condition || 'true'} {`, isBlockStart: true };
        case 'while': return { code: `while ${data.condition || 'true'} {`, isBlockStart: true };
        case 'for': return { code: `for ${data.condition || 'i in 0..10'} {`, isBlockStart: true };
        case 'try': return { code: `// Try-catch not typical in Rust, using simple scope\n{`, isBlockStart: true };

        case 'function': return { code: `fn ${data.label.replace('Def: ', '') || 'my_func'}() {`, isBlockStart: true };
        case 'return': return { code: `return ${data.value || '()'};` };

        case 'python': return { code: `// Raw Python: ${data.label}` };
        case 'comment': return { code: `// ${data.code?.replace('# ', '') || 'Comment'}` };
        default: return { code: `// Unknown: ${type}` };
    }
}
