
import os
import sys
import argparse
import time
from pathlib import Path

# VECTIS Core Integration
VECTIS_ROOT = Path(r"C:\Users\Yuto\Desktop\app\VECTIS_SYSTEM_FILES")
sys.path.append(str(VECTIS_ROOT)) # To find 'modules'

try:
    from modules.gemini_client import GenerativeModel
except ImportError:
    print("⚠️ Warning: Could not import VECTIS modules. Running in mock mode.")
    GenerativeModel = None

# Paths
IDENTITY_FILE = VECTIS_ROOT / "apps" / "CAREER" / "es_assistant" / "IDENTITY_CORE.md"
COMPANIES_DIR = VECTIS_ROOT / "data" / "companies"

class ESGenerator:
    def __init__(self, company_name):
        self.company_name = company_name
        self.model = GenerativeModel() if GenerativeModel else None
        
        self.identity_data = self._load_file(IDENTITY_FILE)
        self.report_path = COMPANIES_DIR / company_name / "REPORT_Soft_Analysis.md"
        self.company_data = self._load_file(self.report_path)
        
        self.output_path = COMPANIES_DIR / company_name / "ES_DRAFT.md"

    def _load_file(self, path):
        if path and path.exists():
            return path.read_text(encoding='utf-8')
        return None

    def generate(self):
        print(f"📝 [AutoES] Generating draft for {self.company_name}...")
        
        if not self.company_data:
            print(f"   ❌ Missing Research Report for {self.company_name}. Cannot generate ES.")
            return False

        if not self.model:
            print("   ⚠️ No LLM available. Skipping generation.")
            return False

        prompt = f"""
You are an expert Career Consultant (ES Architect).
Your task is to write a high-quality Entry Sheet (ES) draft for the user, targeting {self.company_name}.

# 1. Candidate Profile (Identity Core)
{self.identity_data[:3000]}

# 2. Target Company Analysis
{self.company_data[:3000]}

# 3. Task
Write a markdown draft containing:
1.  **志望動機 (Motivation)** (400 chars): Connect the candidate's "Chaos Structuring" or "AI Leadership" to the company's specific values found in the analysis.
2.  **自己PR (Self Promotion)** (400 chars): Highlight the "EGO System" development or Equestrian experience as proof of "Achieving the Impossible".

# Output Format
Markdown. Use Japanese. Tone: Professional, passionate, logical.
"""
        try:
            response_obj = self.model.generate_content(prompt)
            response = response_obj.text
            
            content = f"# ES Draft: {self.company_name}\n\nGenerated by EGO River Flow on {time.strftime('%Y-%m-%d')}\n\n{response}"
            
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.output_path, "w", encoding="utf-8") as f:
                f.write(content)
                
            print(f"   ✅ Saved ES Draft to: {self.output_path}")
            return True
            
        except Exception as e:
            print(f"   ❌ generation failed: {e}")
            return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--company", required=True, help="Target company name")
    args = parser.parse_args()

    generator = ESGenerator(args.company)
    generator.generate()
